### ISSUE TITLE
大神好，down下来之后，npm之后，直接报500错误，咋解决呀？

### ISSUE THREAD

**Issue by dreamlivemeng** [linwh1115/react-native-cnodejs#1]
大神好，down下来之后，npm之后，直接报500错误，咋解决呀？

**Comment by whlin1115** [comment]
可以截图或者贴详细log吗？这个项目从开始到现在都没遇到你说的500错误。。。

**Comment by dreamlivemeng** [comment]
大神，就是报这个。

​

​

2017-09-08 17:26 GMT+08:00 wenhuan <notifications@github.com>:

**Comment by whlin1115** [comment]
@dreamlivemeng 你可能忘记贴截图吧。。。 我猜测你应该npm安装某些依赖的时候，被墙了。换个淘宝镜像或者翻墙试试

**Comment by dreamlivemeng** [comment]
额，我是直接通过邮件回复的，截图好像没贴上来。可能是吧。

**Comment by jintangWang** [comment]
![image](https://user-images.githubusercontent.com/12557847/30799883-e18b04e8-a210-11e7-977d-a08ea7a497b4.png)
就是报这个 - -

**Comment by whlin1115** [comment]
@dreamlivemeng @jintangWang    今天看了下，这个是在安卓上才会出现的 
首先   yarn remove babel-preset-react-native
然后   yarn add --dev babel-preset-react-native@2.1.0
最后 重新编译一边

**Comment by jintangWang** [comment]
@linwh1115 好的，我再试下，前面这样试了没成功

**Comment by jintangWang** [comment]
```
The development server returned response error code: 500

URL: http://10.0.3.2:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false

Body:
{"from":"E:\\react-native\\react-native-cnodejs\\src\\navigation.js","to":"./pages/zone/screen/Setting","message":"Unable to resolve module `./pages/zone/screen/Setting` from `E:\\react-native\\react-native-cnodejs\\src\\navigation.js`: could not resolve `E:\\react-native\\react-native-cnodejs\\src\\pages\\zone\\screen\\Setting' as a folder: it did not contain a package, nor an index file","name":"UnableToResolveError","type":"UnableToResolveError","errors":[{}]}
processBundleResult
    BundleDownloader.java:170
access$100
    BundleDownloader.java:39
onResponse
    BundleDownloader.java:139
execute
    RealCall.java:135
run
    NamedRunnable.java:32
runWorker
    ThreadPoolExecutor.java:1076
run
    ThreadPoolExecutor.java:569
run
    Thread.java:856
```
换了个错

**Comment by whlin1115** [comment]
@dreamlivemeng   这个是因为 在 pages/zone/screen/setting.js 这个文件 setting.js 首字母要大写，
 把 pages/zone/screen/setting.js   改为 Setting.js 就可以了。这个很奇怪我本地是大写的 ，commit 之后变成小写了。我改个名字，重新commit下。  另外今天集成了 聊天，可以实时聊天了。

**Comment by jintangWang** [comment]
@linwh1115 谢谢楼主，楼主真厉害。你是主要做的ios吧，android上bug比较多 - - ，不过还是很强大，手动点赞

**Comment by whlin1115** [comment]
@dreamlivemeng   安卓问题确实有点多，开发的时候主要还是在ios调试的，我再针对安卓做些处理
