### ISSUE TITLE
你这个每个模块组件和业务逻辑处理分开了

### ISSUE THREAD

**Issue by yt7649757** [linwh1115/react-native-cnodejs#2]
我看你的组件是放在component文件夹，相关的js操作，业务逻辑，是放在外面的三个文件中写的，进行拆分了，是这样吗？？？ 我写的只注重功能实现，，而且js和页面上的组件全部混在一个文件中写，感觉比较乱，

**Comment by whlin1115** [comment]
@yt7649757  是的。公共组件放在 最外面的 src/component文件夹中，每个页面如果有单独的组件，那么放在pages/{page}/component里面，如果有其他子页面，那么放在pages/{page}/screen 里面，共用一个页面的state。model.js处理逻辑，index.js负责页面结构，service.js负责处理数据（如果数据不是很多，那么可以吧service.js的代码写在model.js）个人感觉这样新建一个页面可能快，结构也比较清晰
