### ISSUE TITLE
请问发布新帖app会推送通知吗

### ISSUE THREAD

**Issue by ColinXXT** [linwh1115/react-native-cnodejs#5]

**Comment by linwh1115** [comment]
系统通知没有做，只有软件里面的通知

**Comment by whlin1115** [comment]
@ColinXXT   系统通知没有做，只有软件里面的通知

**Comment by ColinXXT** [comment]
谢谢，我想做个ios系统推送，这个能关联起来吗或者有什么资料可以推荐下？发自我的iPhone------------------ 原始邮件 ------------------发件人: wenhuan  <notifications@github.com>发送时间: 2017年10月10日 09:36收件人: linwh1115/react-native-cnodejs <react-native-cnodejs@noreply.github.com>抄送: Colin <h2uimzk9p@126.com>, Mention <mention@noreply.github.com>主题: 回复：[linwh1115/react-native-cnodejs] 请问发布新帖app会推送通知吗 (#5)@ColinXXT   系统通知没有做，只有软件里面的通知

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/linwh1115/react-native-cnodejs","title":"linwh1115/react-native-cnodejs","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/linwh1115/react-native-cnodejs"}},"updates":{"snippets":[{"icon":"PERSON","message":"@linwh1115 in #5: @ColinXXT   系统通知没有做，只有软件里面的通知"}],"action":{"name":"View Issue","url":"https://github.com/linwh1115/react-native-cnodejs/issues/5#issuecomment-335334043"}}}

**Comment by whlin1115** [comment]
@ColinXXT   参考 https://github.com/fangwei716/30-days-of-react-native/blob/development/view/day30.js
