### ISSUE TITLE
无法启动packager！！！

### ISSUE THREAD

**Issue by mengerzhuanyong** [linwh1115/react-native-cnodejs#7]
<img width="1025" alt="qq20171013-113652 2x" src="https://user-images.githubusercontent.com/19523478/31529295-f66be220-af9d-11e7-9094-e965e0589555.png">
packager启动不了，出现了上面的错误。

**Comment by whlin1115** [comment]
@mengerzhuanyong   node 版本多少？先删除node_modules 文件夹，重新 npm install 。或者 npm install lodash --save

**Comment by imwr** [comment]
遇到同样的问题~~~node是9.2版本
@linwh1115 你用的哪个版本？

**Comment by whlin1115** [comment]
@imwr  8.1

**Comment by imwr** [comment]
@linwh1115 这个demo里面，有实现 获取环信所有好友最后一条消息和未读消息数功能吗？望指点下。

**Comment by whlin1115** [comment]
@imwr   有处理好友未读消息数，和获取未读信息。

**Comment by garyhu1** [comment]
我的版本是8.9的，也遇到这样的问题，除了版本的问题外还怎么处理啊，我删除了node-module,然后重新npm install了，还是会这样啊

**Comment by whlin1115** [comment]
@garyhu1  先用 8.1 版本 ， nvm    node版本控制
