### ISSUE TITLE
对node有版本限制嘛

### ISSUE THREAD

**Issue by garyhu1** [linwh1115/react-native-cnodejs#8]
![image](https://user-images.githubusercontent.com/19940612/34932296-4695cc66-fa0d-11e7-883f-5b1d6802fa07.png)

我的node是8.9.1，

**Comment by whlin1115** [comment]
@garyhu1    暂时先用8.1 的版本吧，过段时间我再升级下 一些模块

**Comment by garyhu1** [comment]
还是同样的问题，我是运行到Android手机上的

![image](https://user-images.githubusercontent.com/19940612/34976318-fdf7d192-fad0-11e7-869f-5679239d9d64.png)

**Comment by whlin1115** [comment]
@garyhu1    切换版本后 重新 npm i 了？

**Comment by garyhu1** [comment]
换了版本后，我删除了node_module,然后运行了npm install    就又出现上面那些错误，

**Comment by garyhu1** [comment]
最近有个做聊天的需求，不知道怎么集成，其实就想问问您是怎么集成成功的，有什么需要注意的地方嘛。或者加一个QQ沟通下可以嘛

**Comment by garyhu1** [comment]
我的扣扣942984941

**Comment by whlin1115** [comment]
@garyhu1   尝试使用 yarn 安装。因为这个项目之前 使用yarn的。用npm 安装，我在新电脑上确实有些问题

**Comment by garyhu1** [comment]
好吧

**Comment by whlin1115** [comment]
@garyhu1   集成聊天那块 在 src/pages/notice  index.js 里面，你可以先看看，环信官方文档也介绍的比较清楚了

**Comment by garyhu1** [comment]
好的，谢谢大神指点
